/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.28).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import io.swagger.model.CreateOrderDTO;
import io.swagger.model.Order;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-09-10T22:37:01.163Z")

@Validated
@Api(value = "orders", description = "the orders API")
@RequestMapping(value = "/orders/")
public interface OrdersApi {

    @ApiOperation(value = "Retorna os pedidos do usuario", nickname = "ordersUserGet", notes = "", response = Order.class, responseContainer = "List", authorizations = {
        @Authorization(value = "Bearer")
    }, tags={ "orders", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Sucesso", response = Order.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Sem autorizacao") })
    @RequestMapping(value = "/",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Order>> ordersUserGet();


    @ApiOperation(value = "Cria um cupom para um usuario", nickname = "ordersUserPost", notes = "", authorizations = {
        @Authorization(value = "Bearer")
    }, tags={ "orders", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Criado"),
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<?> ordersUserPost(@Valid @RequestBody CreateOrderDTO body);

}
