/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.28).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import io.swagger.model.Order;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-09-10T22:37:01.163Z")

@Validated
@Api(value = "order", description = "the order API")
@RequestMapping(value = "/order/")
public interface OrderApi {

    @ApiOperation(value = "Deleta o pedido", nickname = "orderOrderIdDelete", notes = "", authorizations = {
            @Authorization(value = "Bearer")
    }, tags = {"order",})
    @ApiResponses(value = {
            @ApiResponse(code = 204, message = "Deletado com sucesso"),
            @ApiResponse(code = 400, message = "Esse pedido não existe ou você não pode deleta-lo"),
            @ApiResponse(code = 404, message = "Pedido não encontrado")})
    @RequestMapping(value = "{orderId}",
            produces = {"application/json"},
            method = RequestMethod.DELETE)
    ResponseEntity<?> orderOrderIdDelete(@ApiParam(value = "Id do pedido a ser deletado", required = true) @PathVariable("orderId") Long orderId);


    @ApiOperation(value = "Retorna um pedido", nickname = "orderOrderIdGet", notes = "", response = Order.class, authorizations = {
            @Authorization(value = "Bearer")
    }, tags = {"order",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Sucesso", response = Order.class),
            @ApiResponse(code = 204, message = "Pedido não encontrado"),
            @ApiResponse(code = 401, message = "Sem autorizacao")})
    @RequestMapping(value = "{orderId}",
            produces = {"application/json"},
            method = RequestMethod.GET)
    ResponseEntity<?> orderOrderIdGet(@ApiParam(value = "ID do usuário", required = true) @PathVariable("orderId") Long orderId);


    @ApiOperation(value = "Atualizar um pedido", nickname = "orderOrderIdPut", notes = "Usado apenas para invalidar o cupom", authorizations = {
        @Authorization(value = "Bearer")
    }, tags={ "order", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Atualizado com sucesso"),
        @ApiResponse(code = 401, message = "Nao autorizado"),
        @ApiResponse(code = 404, message = "Pedido nao encontrado") })
    @RequestMapping(value = "{orderId}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> orderOrderIdPut(@ApiParam(value = "",required=true) @PathVariable("orderId") Long orderId,@ApiParam(value = "" ,required=true )  @Valid @RequestBody Order body);

    @ApiOperation(value = "Valida se o cupom é válido", nickname = "orderCouponValidGet", notes = "", response = Order.class, authorizations = {
            @Authorization(value = "Bearer")
    }, tags={ "order", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Sucesso", response = Order.class),
            @ApiResponse(code = 401, message = "Sem autorizacao") })
    @RequestMapping(value = "validate/{couponCode}",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<Order> orderCouponValidGet(@ApiParam(value = "Código do cupom",required=true) @PathVariable("couponCode") String couponCode);

    @ApiOperation(value = "Dá a baixa no cupom", nickname = "orderCouponFinishGet", notes = "", response = Order.class, authorizations = {
            @Authorization(value = "Bearer")
    }, tags={ "order", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Sucesso", response = Order.class),
            @ApiResponse(code = 401, message = "Sem autorizacao") })
    @RequestMapping(value = "finish/{couponCode}",
            produces = { "application/json" },
            method = RequestMethod.GET)
    ResponseEntity<Order> orderCouponFinishGet(@ApiParam(value = "Código do cupom",required=true) @PathVariable("couponCode") String couponCode);
}
